---
title: "Partie_2"
author: "AmigoTeam"
date: "2024-04-09"
output: html_document
---
# Une modèle pour déterminer l'importance des impacts variables des ouragans sur le long terme des récifs corailiens. 

Par Antoince Castonguay et Félix Richard. L'AmigoTeam.  
antoine.castonguay@usherbrooke.ca  
felix.richard@usherbrooke.ca  

## Introduction
Pour lutter contre la dégradation des récifs coralliens, il est crucial d'agir pour préserver cette ressource inestimable qui favorise la biodiversité des océans. Le modèle développé par Blackwood, J.C., Hastings, A. et Mumby, P.J. en 2011 est particulièrement intéressant, car il décrit bien les effets de plusieurs stress et leurs interactions sur la survie des coraux à long terme. 

Ils aborent premierement la compétition de l'espace entre les macroalgue et les coraux. Deuxiemement, ils ajoute au modele la relation consomateur-ressource entre les parrofishs et les macroalgues. En troisieme lieu, la rugosité des coraux est également considérée comme un élément crucial pour la capacité de soutien des populations de parrofishs, tandis que l'effort de pêche joue un rôle important sur la population de parrofishs. Enfin, le modèle inclut un élément stochastique représentant les ouragans, qui ont un impact sur les populations de coraux, de macroalgues et sur la rugosité des coraux. 

Dans notre étude, nous avons cherché à rendre ce modèle plus réaliste en y ajoutant une composante plus variable et aléatoire simulant de manière plus précise l'impact réel des ouragans. De plus, nous avons intégré une augmentation de la fréquence des ouragan au fil des années, ce qui reflète la situation actuelle avec les changements climatiques.

## Méthode

Mise en œuvre d'un modele avec des ouragan stochastique:  
##### $dC = g_C(C,M,P,R,t)dt - c(F()+\sigma \epsilon)idq$  
##### $dM = g_M(C,M,P,R,t)dt - Mm_Hdqi$  
##### $dP = g_P(C,M,P,R,t)dt$  
$dR = g_R(C,M,P,R,t)dt - (R-1)(G() + \sigma \epsilon)idq$  
$dY = 1 - M - C$  

$g_C(C,M,P,R,t) = rTC - dC - aMC$  
$g_M(C,M,P,R,t) = aMC - \frac{\alpha \frac{P}{\beta}M}{M + Y} - \gamma MY$  
$g_P(C,M,P,R,t) = sP(1 - \frac{P}{\beta K(M+T,R)} - sfP$  
$g_R(C,M,P,R,t) = h_GC(3-R) - h_E(1-C)(R-1)$  

$K(M+T,R) = \frac{(c1R + c2)}{K_{max}}\frac{\delta(M+Y)}{1 + v(M+Y)}$

$F() = 0.0512 + 0.0176*te$ avec un maximun de F() = 0.5.

| Paramètre | Valeur | Définition |
|--|--|--|
| s | 0.49 | Taux de croissance du parrofish par année |
| r | 1 |  Taux pour lequel le corail remplace le gazon d'algue par année (Taux de coissance du corail)|
| a | 0.1 | Taux pour lequel les macroalgues remplace le corail par année |
| gamma | 1.6,0.8 | Taux pour lequel les macroalgues remplace le gazon d'algue par année |
| d | 0.44 | Taux de mortalité du corail par année |
| Alpha | 1 | Taux de broutage maximale par le parrofish |
| f | variable | Effort de pêche en pourcentage |
| c1,c2 | 3.65,-3.21 | Détermine la relation entre la complexité du corail et la capacité de support du parrofish |
| delta,v | 4.557,0.9877 | Détermine la relation entre la nourriture disponible et la capacité de support du parrofish |
| Beta | 1 | Capacité de support de l'environnement pour le parrofish théorique et relatif |
| hG | 0.03 | Rétablissement de la complexité du corail par année |
| hE | 0.01 | Érosion de la complexité du corail par année |
| kmax | 17.745 | Limite supérieure d'abondance des parrofishs |
| F() | 0.0512 + 0.0176*te | La proportion de la couverture corallienne maximun affectée par un ouragan respectivement |
| G() |  | La proportion attendue de rugosité affectée au maximun par les impacts des ouragans respectivement |
| mH | 0.8 | Taux de mortalité des macroalgues maximun suite a un ouragan |
| te | varaible | Temps écouler depuis le dernier ouragan en année |
| sigma | 0.05 | Écart maximale de la variabilité des impacts des oragans d'epsilon |
| epsilon | entre 0 et 1 | Variable aléatoire suivant une distribution normale standard qui décrit la composante aléatoire des impacts des oragans sur le corail |
| i | entre 0 et 1 | Pourcentage d'impacte des ouragants |

| Variable | Valeur possible | Définition |
|--|--|--|
| R | entre 1 et 3 | Correspond à la rugosité des recif corralien. Où 1 équivaut à une structrue parfaitement lisse et où 3 est un rugosité très pronnoncer rarement atteint qui équivaut a un récif corailien offrant une tres bonne qualité d'habitat.
| C | entre 0 et 1 | Correspond à la proportion de couverture du paysage par le corail. Où 1 est une couverture complete et où 0 est l'extinction des corail. |
| M | entre 0 et 1 | Correspond à la proportion de couverture du paysage par les macroalgues. Où 1 est une couverture compete et où 0 est l'extinction des macroalgue. |
| Y | entre 0 et 1 | Le gazon d'algue correspond a tout ce qui n'est pas corail et macroalgue. |
| P | entre 0 et 1 | Correspond à la population des parrofishs. Où 1 est lorsque la capacité de support maximale est atteind et où 0 est l'extinction des parrofishs |

## Résultat
Présenter les graphiques 
