---
title: "Projet BIO401"
author: "AmigoTeam"
date: "2024-04-07"
output: html_document
---

Partie 1 :

Question biologique : 

Est ce que la résilience des récifs coraliens est suffisante pour lutter contre les facteur de stress tels que la surpêche et les ouragans? 

Hypothèse :

Elle est suffisante jusqu'à une certaine limite qui dépend beaucoup de la complexité du corail, le l'effort de pêche et de l'impact aléatoire des ouragans.

Données :  

| Paramètre | Valeur | Définition |
|--|--|--|
| s | 0.49 | Taux de croissance du parrofish par année |
| r | 1,0.8 | Taux de coissance du corail et taux pour lequel le corail remplace le gazon d'algue par année |
| a | 0.1 | Taux pour lequel les macroalgues remplace le corail par année |
| gamma | 1.6,0.8 | Taux pour lequel les macroalgues remplace le gazon d'algue par année |
| d | 0.44 | Taux de mortalité du corail par année |
| Alpha | 1 | Taux de broutage maximale par le parrofish |
| f | variable | Effort de pêche en pourcentage |
| c1,c2 | 3.65,-3.21 | Détermine la relation entre la complexité du corail et la capacité de support du parrofish |
| delta,v | 4.557,0.9877 | Détermine la relation entre la nourriture disponible et la capacité de support du parrofish |
| Beta | variable | Capacité de support de l'environnement pour le parrofish |
| hG | 0.03 | Rétablissement de la complexité du corail par année |
| hE | 0.01 | Érosion de la complexité du corail par année |
| kmax | 17.745 | Limite supérieure d'abondance des parrofishs |
| F | 0.0512 + 0.0176*te, 0 | La proportion de la couverture corallienne affectée par un ouragan respectivement fort/moyen et faible |
| G | 0.5, F, 0.05 | La proportion attendue de rugosité affectée par les impacts des ouragans respectivement fort, moyen et faible |
| mH | 0.8 | Taux de mortalité des macroalgues suite a un ouragan |
| te | varaible | Temps écouler depuis le dernier ouragan en année |
| sigma | 0.05 | Écart maximale de la variabilité des impacts des oragans d'epsilon |
| epsilon | entre 0 et 1 | Variable aléatoire suivant une distribution normale standard qui décrit la composante aléatoire des impacts des oragans sur le corail |

| Paramètre | Valeur possible | Définition |
|--|--|--|
| R | entre 1 et 3 | Où 1 équivaut à un structrue des récif coralien parfaitement lisse et où 3 est un rugosité très pronnoncer rarement atteint qui équivaut a un récif corailien en tres bonne santé |
| C | entre 0 et 1 | Où 1 est une couverture complete des corail et 0 l'extinction des corail |
| M | entre 0 et 1 | Où 1 est une couverture complete des macroalgue et 0 l'extinction des macroalgue |
| Y | entre 0 et 1 | Le gazon d'algue correspond a tout ce qui n'est pas corail et macroalgue |
| P | entre 0 et 1 | Où 1 est lorsque la capacité de support maximale est atteind et 0 est l'extinction des parrofishs |

Méthode :

modele de base :  
$\frac{dM}{dt} = aMC - \frac{g(P)M}{M + Y} - \gamma MY$  
$\frac{dC}{dt} = rTC - dC - aMC$  
$\frac{dP}{dt} = sP(1 - \frac{P}{\beta K(C)}) - fP$  
$\frac{dY}{dt} = 1 - M - C$  

$g(P) = \alpha (\frac{P}{\beta})$  
si Beta est relatif donc 1  
$g(P)= \alpha P$  

La capacité de support de l'environnement, initialement définie en fonction de la couverture corallienne K(C), a été modifiée pour prendre en compte l'abondance des algues, qui constituent leur nourriture, ainsi que la qualité de l'habitat K(M + T, R).  
$K(M+T,R) = \frac{(c1R + c2)}{K_{max}}\frac{\delta(M+Y)}{1 + v(M+Y)}$

Les changements lents de la rugosité, qui se produisent entre les ouragans et résultent de la production des coraux qui construisent les récifs et de la bioérosion, ont été intégrés au modèle.  
$\frac{dR}{dt} = h_GC(3-R) - h_E(1-C)(R-1)$

Modele améliorer :
$\frac{dM}{dt} = aMC - \frac{\alpha PM}{M + Y} - \gamma MY$  
$\frac{dC}{dt} = rTC - dC - aMC$  
$\frac{dP}{dt} = sP(1 - \frac{P}{K(M+T,R)} - fP$  
$\frac{dR}{dt} = h_GC(3-R) - h_E(1-C)(R-1)$  
$\frac{dY}{dt} = 1 - M - C$  

Mise en œuvre d'un ouragan stochastique:
$dC = g_C(C,M,P,R,t)dt - c(F+\sigma \epsilon)dq$
$dM = g_M(C,M,P,R,t)dt - Mm_Hdq$
$dP = g_P(C,M,P,R,t)dt$
$dR = g_R(C,M,P,R,t)dt - (R-1)(G + \sigma \epsilon)dq$
où $g_C,g_M,g_P,g_R$ sont identique au patie correpondant du modele améliorer.
où q est un processus de saut de Poisson avec un taux de saut λ tel que dq = 0 avec une probabilité de 1 - λdt et dq = 1 avec une probabilité de λdt.

Supposition :

Calcul :

Résultat :

Interprétation : 
